export default {
  login: 'ujol991',
  id: 85609516,
  node_id: 'MDQ6VXNlcjg1NjA5NTE2',
  avatar_url: 'https://avatars.githubusercontent.com/u/85609516?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/ujol991',
  html_url: 'https://github.com/ujol991',
  followers_url: 'https://api.github.com/users/ujol991/followers',
  following_url: 'https://api.github.com/users/ujol991/following{/other_user}',
  gists_url: 'https://api.github.com/users/ujol991/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/ujol991/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/ujol991/subscriptions',
  organizations_url: 'https://api.github.com/users/ujol991/orgs',
  repos_url: 'https://api.github.com/users/ujol991/repos',
  events_url: 'https://api.github.com/users/ujol991/events{/privacy}',
  received_events_url: 'https://api.github.com/users/ujol991/received_events',
  type: 'User',
  site_admin: false,
  name: 'ujol maharjan',
  company: 'User Interafce Reseacrh',
  blog: '',
  location: 'kathmandu,Nepal',
  email: null,
  hireable: null,
  bio: 'Front end Developer (ReactJs, Vue Js) and Designer',
  twitter_username: 'uzzalmaharjan1',
  public_repos: 3,
  public_gists: 0,
  followers: 3,
  following: 2,
  created_at: '2021-06-09T07:36:25Z',
  updated_at: '2021-08-26T07:30:07Z',
}
