export default [
  {
    login: 'mxmnk',
    id: 46030850,
    node_id: 'MDQ6VXNlcjQ2MDMwODUw',
    avatar_url: 'https://avatars.githubusercontent.com/u/46030850?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mxmnk',
    html_url: 'https://github.com/mxmnk',
    followers_url: 'https://api.github.com/users/mxmnk/followers',
    following_url: 'https://api.github.com/users/mxmnk/following{/other_user}',
    gists_url: 'https://api.github.com/users/mxmnk/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mxmnk/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mxmnk/subscriptions',
    organizations_url: 'https://api.github.com/users/mxmnk/orgs',
    repos_url: 'https://api.github.com/users/mxmnk/repos',
    events_url: 'https://api.github.com/users/mxmnk/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mxmnk/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'zendy199x',
    id: 50132805,
    node_id: 'MDQ6VXNlcjUwMTMyODA1',
    avatar_url: 'https://avatars.githubusercontent.com/u/50132805?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/zendy199x',
    html_url: 'https://github.com/zendy199x',
    followers_url: 'https://api.github.com/users/zendy199x/followers',
    following_url:
      'https://api.github.com/users/zendy199x/following{/other_user}',
    gists_url: 'https://api.github.com/users/zendy199x/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/zendy199x/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/zendy199x/subscriptions',
    organizations_url: 'https://api.github.com/users/zendy199x/orgs',
    repos_url: 'https://api.github.com/users/zendy199x/repos',
    events_url: 'https://api.github.com/users/zendy199x/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/zendy199x/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Eloparto',
    id: 80689369,
    node_id: 'MDQ6VXNlcjgwNjg5MzY5',
    avatar_url: 'https://avatars.githubusercontent.com/u/80689369?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Eloparto',
    html_url: 'https://github.com/Eloparto',
    followers_url: 'https://api.github.com/users/Eloparto/followers',
    following_url:
      'https://api.github.com/users/Eloparto/following{/other_user}',
    gists_url: 'https://api.github.com/users/Eloparto/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Eloparto/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Eloparto/subscriptions',
    organizations_url: 'https://api.github.com/users/Eloparto/orgs',
    repos_url: 'https://api.github.com/users/Eloparto/repos',
    events_url: 'https://api.github.com/users/Eloparto/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Eloparto/received_events',
    type: 'User',
    site_admin: false,
  },
]
